version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    container_name: auto-number-fe-c
    image: auto-number-fe-i
    restart: always
    networks:
      - xs-network

networks:
  xs-network:
    external: true