version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3838:3838'
    container_name: auto-number-api-c
    image: auto-number-api-i
    restart: always
    networks:
      - xs-network

networks:
  xs-network:
    external: true